import { BalanceLevel, BalanceType, BodyFocus, ContractionType, Equipment, ExerciseTarget, Joint, LiftType, MovementPattern, MovementPlane, MuscleGroup, PrismaClient, Role, StretchType } from "@prisma/client";
const db = new PrismaClient();

function createUser() {
  return db.user.create({
    data: {
      role: Role.user,
      email: "testuser@email.com",
      firstName: "Test",
      lastName: "User"
    }
  })
}

function createAdmin() {
  return db.user.create({
    data: {
      role: Role.admin,
      email: "coach.mkillebrew@gmail.com",
      firstName: "Coach",
      lastName: "Killebrew"
    }
  })
}

function getCoaches() {
  return [
    {
      name: "Mark"
    },
    {
      name: "Rae"
    }
  ]
}

function getKettlebellExercises() {
  return [
    // {
    //   name: "Kettlebell Goblet Squat",
    //   description: "A lower body compound squat exercise that uses a single kettlebell as the load",
    //   tags: ["deep squat", "goblet", "functional"],
    //   cues: [
    //     "Hold the kettlebell to your chest with your elbows in",
    //     "Stand with feet about hip width apart with toes slightly pointed outwards",
    //     "Lower like you are sitting on a small chair below you, then drive through the feet to stand"
    //   ],
    //   tips: [
    //     "Breath in as you descend, exhale as you ascend",
    //     "Keep your elbows pinned to your sides throughout the descent and ascent",
    //     "Keep knees pushed out and chest up throughout the movement"
    //   ],
    //   balance: BalanceType.bilateral,
    //   balanceLevel: BalanceLevel.static,
    //   body: [BodyFocus.lower],
    //   contraction: ContractionType.isotonic,
    //   equipment: [Equipment.kettlebell],
    //   joint: [Joint.ankle, Joint.knee, Joint.hip],
    //   lift: LiftType.compound,
    //   muscles: [MuscleGroup.glutes, MuscleGroup.hamstrings, MuscleGroup.quads, MuscleGroup.erectors],
    //   pattern: [MovementPattern.squat],
    //   plane: [MovementPlane.sagittal],
    // },
    // {
    //   name: "Kettlebell Sumo Deadlift",
    //   description: "A lower body compound hinge exercise that uses a single kettlebell as the load",
    //   tags: ["functional", "booty"],
    //   cues: [
    //     "Stand with feet slightly wider than hip width directly over kettlebell",
    //     "Lower by pushing your hips back and grip the kettlebell tight",
    //     "Drive through the feet to stand, push hips back to lower"
    //   ],
    //   tips: [
    //     "Breath in as you descend, exhale as you ascend",
    //     "Keep good posture throughout the movement: think shoulders back and chest out",
    //     "Keep knees pushed out and chest up throughout the movement"
    //   ],
    //   balance: BalanceType.bilateral,
    //   balanceLevel: BalanceLevel.static,
    //   body: [BodyFocus.lower],
    //   contraction: ContractionType.isotonic,
    //   equipment: [Equipment.kettlebell],
    //   joint: [Joint.ankle, Joint.knee, Joint.hip],
    //   lift: LiftType.compound,
    //   muscles: [MuscleGroup.glutes, MuscleGroup.hamstrings, MuscleGroup.erectors, MuscleGroup.lats],
    //   pattern: [MovementPattern.hinge],
    //   plane: [MovementPlane.sagittal],
    // },
    {
      name: "Half Kneel Kettlebell Press",
      description: "An upper body compound press exercise that uses a single kettlebell as the load",
      tags: ["functional", "stability"],
      cues: [
        "Start in a half-kneeling position with one knee down and the other foot forward. Hold the kettlebell in the hand opposite the down knee, racked at the shoulder.",
        "Brace your core and keep elbow pinned to side.",
        "Press the kettlebell overhead until your arm is straight. Lower the kettlebell with control back to the starting position."
      ],
      tips: [
        "Breath in before the rep and exhale as you press",
        "Avoid winging your elbow during the press",
        "Avoid leaning back or to the side during the press"
      ],
      balance: BalanceType.unilateral,
      balanceLevel: BalanceLevel.static,
      body: [BodyFocus.upper, BodyFocus.core],
      contraction: ContractionType.isotonic,
      equipment: [Equipment.kettlebell],
      joint: [Joint.shoulder, Joint.elbow, Joint.wrist],
      lift: LiftType.compound,
      muscles: [MuscleGroup.shoulders, MuscleGroup.triceps, MuscleGroup.serratus],
      pattern: [MovementPattern.push],
      plane: [MovementPlane.sagittal, MovementPlane.frontal],
      muxPlaybackId: "TU4XmFZXrsRuP5pI4kPLFV7rGuOijeFqZF2vt01983O8",
    },
    // {
    //   name: "Kettlebell Single Leg Deadlift",
    //   description: "A lower body compound hinge exercise that requires single leg balance",
    //   tags: ["functional", "stability", "sldl", "balance"],
    //   cues: [
    //     "Hold the kettlebell in one hand and stand with a staggered stance",
    //     "Lower the kettlebell and hinge your hips",
    //     "Drive through the floor to return to starting position"
    //   ],
    //   tips: [
    //     "Maintain a lengthened spine",
    //     "Breathe in as you lower and exhale as you stand",
    //   ],
    //   balance: BalanceType.unilateral,
    //   balanceLevel: BalanceLevel.dynamic,
    //   body: [BodyFocus.lower, BodyFocus.core],
    //   contraction: ContractionType.isotonic,
    //   equipment: [Equipment.kettlebell],
    //   joint: [Joint.ankle, Joint.knee, Joint.hip],
    //   lift: LiftType.compound,
    //   muscles: [MuscleGroup.glutes, MuscleGroup.hamstrings, MuscleGroup.adductors, MuscleGroup.obliques, MuscleGroup.lats],
    //   pattern: [MovementPattern.hinge, MovementPattern.rotational],
    //   plane: [MovementPlane.sagittal, MovementPlane.frontal],
    // },
    {
      name: "Kettlebell Renegade Row",
      description: "A full body stability and strength exercise that combines the plank and row",
      tags: ["functional", "stability", "renegade"],
      cues: [
        "Get in push up position with each hand on a kettlebell",
        "Push down on one kettlebell as you row the other by pulling the elbow to your side",
        "Lower the kettlebell with control and alternate each side"
      ],
      tips: [
        "Maintain a lengthened spine and keep your legs straight",
        "Widen the stance of your feet to reduce the stability demand"
      ],
      balance: BalanceType.unilateral,
      balanceLevel: BalanceLevel.dynamic,
      body: [BodyFocus.full, BodyFocus.core, BodyFocus.upper],
      contraction: ContractionType.isotonic,
      equipment: [Equipment.kettlebell],
      joint: [Joint.shoulder, Joint.elbow, Joint.wrist, Joint.ankle],
      lift: LiftType.compound,
      muscles: [MuscleGroup.serratus, MuscleGroup.obliques, MuscleGroup.lats, MuscleGroup.erectors, MuscleGroup.abs],
      pattern: [MovementPattern.pull, MovementPattern.rotational],
      plane: [MovementPlane.sagittal, MovementPlane.transverse],
      muxPlaybackId: "qXmm5l2CxN2thr6tMujWLajg34eThU00p5y01lVfm2vXg",
    },
    {
      name: "Kettlebell Swing",
      description: "A full body power exercise that emulates jumping",
      tags: ["functional", "power", "jump", "athletic", "speed", "booty"],
      cues: [
        "Postion the kettlebell in front of you and stand with the feet shoulder width apart",
        "Push your hips back, like you are closing a door with your butt, and extend your arms forward to grab the kettlebell with both hands",
        "Throw the kettlebell back between your legs, like a football snap, then thrust your hips forward quickly to initiate the swing"
      ],
      tips: [
        "A progression of the kettlebell sumo deadlift",
        "Emulates jumping or other adult activities",
        "Keep arms and shoulders relaxed throughout the motion",
      ],
      balance: BalanceType.bilateral,
      balanceLevel: BalanceLevel.static,
      body: [BodyFocus.lower, BodyFocus.core, BodyFocus.full],
      contraction: ContractionType.isotonic,
      equipment: [Equipment.kettlebell],
      joint: [Joint.ankle, Joint.knee, Joint.hip],
      lift: LiftType.compound,
      muscles: [MuscleGroup.glutes, MuscleGroup.hamstrings, MuscleGroup.lats, MuscleGroup.erectors, MuscleGroup.abs],
      pattern: [MovementPattern.hinge, MovementPattern.core],
      plane: [MovementPlane.sagittal],
      muxPlaybackId: "qXmm5l2CxN2thr6tMujWLajg34eThU00p5y01lVfm2vXg"
    },
  ];
};

function getAthleticConditioningExercises() {
  return [
    {
      name: "Half Kneeling Adductor Rock",
      description: "A lower body dynamic stretch that improves hip mobility",
      tags: ["functional", "activation", "adductors"],
      cues: [
        "Start in a tabletop position, on hands and knees, with one leg extended fully to the side. Your spine should be straight and neck relaxed.",
        "Inhale deeply through the nose. Then slowly exhale, like blowing through a straw, while driving the hips back to your feet. Only drive the hips back as far as you can without rounding your back.",
        "Come back to the starting position and repeat for desired number of repetitions. You should feel a deep stretch in the inner thigh (adductor) of your extended leg.",
        "Repeat with opposite leg."
      ],
      body: [BodyFocus.lower],
      contraction: ContractionType.isotonic,
      equipment: [Equipment.bodyweight],
      joint: [Joint.hip],
      muscles: [MuscleGroup.adductors, MuscleGroup.abs],
      pattern: [MovementPattern.squat, MovementPattern.lunge, MovementPattern.core],
      plane: [MovementPlane.sagittal],
      stretch: StretchType.dynamic,
      muxPlaybackId: "Ep00hFh29GqHiP00r00pMFSRlCOfJAdddgdDiAENY01i6qI",
    },
    {
      name: "90/90 ER/IR Hip Stretch",
      description: "A lower body dynamic stretch that improves hip mobility",
      tags: ["functional", "activation", "glutes"],
      cues: [
        "Sit on the floor with both legs in a 90/90 position: one leg in front with the knee bent at 90 degrees and the other leg behind, also bent at 90 degrees. Sit with the torso upright",
        "While keeping a lengthened spine, exhale and drive the chest towards the front knee. Only drive as far as you can without rounding your back.",
        "Pause momentarily in the stretched position before returning to the start position. Repeat for the desired number of repetitions. You should feel the stretch in the hip (glute) of the front leg.",
        "Repeat with opposite leg."
      ],
      body: [BodyFocus.lower],
      contraction: ContractionType.isotonic,
      equipment: [Equipment.bodyweight],
      joint: [Joint.hip],
      muscles: [MuscleGroup.glutes],
      pattern: [MovementPattern.squat, MovementPattern.lunge],
      plane: [MovementPlane.transverse],
      stretch: StretchType.static,
      muxPlaybackId: "vBU0063pFAXYUcfeQiPWJokcLFaC4jh8KU8PFtrQsiYI",
    },
    {
      name: "Adductor Foam Roll",
      description: "A lower body myofascial release technique",
      tags: ["functional", "foam rolling", "adductors"],
      cues: [
        "Lie face down with one leg extended to the side, and place the foam roller under the inner thigh of that leg.",
        "Gently roll along the inner thigh from the groin to just above the knee, applying moderate pressure.",
        "Focus on tender spots. You should feel a release in the adductors (inner thigh). Avoid applying too much pressure.",
        "Repeat with opposite leg."
      ],
      body: [BodyFocus.lower],
      equipment: [Equipment.bodyweight, Equipment.foam_roller],
      joint: [Joint.hip],
      muscles: [MuscleGroup.adductors],
      pattern: [MovementPattern.squat, MovementPattern.lunge],
      plane: [MovementPlane.frontal],
      muxPlaybackId: "GQa5WWwzNCwfamKzjMDcyJY1Z3bT29BoArujL4YPTjs",
    },
    {
      name: "Ankle Mobility",
      description: "A lower body myofascial release technique",
      tags: ["calves", "mobility"],
      cues: [
        "Stand facing a wall with one foot forward and one foot back, both feet flat on the ground.",
        "Drive your front knee forward towards the wall, keeping your heel down. Move the knee laterally to increase mobility in all directions.",
        "You should feel the stretch in your calf and ankle. Focus on improving ankle dorsiflexion and overall range of motion.",
        "Repeat with opposite leg."
      ],
      body: [BodyFocus.lower],
      equipment: [Equipment.bodyweight],
      joint: [Joint.ankle],
      muscles: [MuscleGroup.calves],
      pattern: [MovementPattern.squat, MovementPattern.lunge],
      plane: [MovementPlane.sagittal],
      stretch: StretchType.dynamic,
      muxPlaybackId: "00D40000iYKRrC8HVKs501wQbddgiQXp01WehdItlacgmLag",
    },
    {
      name: "Band Assisted Leg Lowering",
      description: "A lower body drill for activating the posterior chain and core",
      tags: ["activation", "posterior chain"],
      cues: [
        "Lie on your back with both legs extended towards the ceiling. Wrap a resistance band around the arch of one foot, holding the other end with your hands. Keep the other leg extended toward the ceiling.",
        "Lower your leg slowly towards the ground while keeping your core tight and lower back pressed into the floor. Use the band to assist in controlling the motion.",
        "Finish when your leg is close to the ground, then return to the start position. Repeat for desired number of repetitions. You should feel the stretch in your hamstrings and activation in your core.",
        "Repeat with opposite leg."
      ],
      body: [BodyFocus.lower],
      equipment: [Equipment.bodyweight, Equipment.resistance_band],
      joint: [Joint.hip, Joint.knee, Joint.ankle],
      muscles: [MuscleGroup.glutes, MuscleGroup.hamstrings, MuscleGroup.erectors],
      pattern: [MovementPattern.squat, MovementPattern.lunge],
      plane: [MovementPlane.sagittal],
      muxPlaybackId: "N602azha2Y3XjCw4QkJcbrGH6TzIYS02ZE2PegWcsvN00g",
    },
    {
      name: "Upper Back Foam Roll",
      description: "An upper body myofascial release technique",
      tags: ["foam roller", "thoracic spine"],
      cues: [
        "Lie on your back with the foam roller placed horizontally under your upper back. Cross your arms in front of you to move your shoulder blades out of the way.",
        "Roll slowly from the middle of your back to just below your shoulder blades, pausing on tight or sore spots.",
        "Focus on relieving tension in the upper back. You should feel the muscles in your upper back relaxing and releasing tension."
      ],
      body: [BodyFocus.upper],
      equipment: [Equipment.bodyweight, Equipment.foam_roller],
      muscles: [MuscleGroup.lats, MuscleGroup.traps],
      muxPlaybackId: "lq2ZVeykjOh45SUNWoiwM00tu02qcajnInczgDo4rGdSg",
    },
    {
      name: "Standing Medicine Ball Chest Pass",
      description: "An upper body power movement that targets chest",
      tags: ["power", "plyometric", "chest", "arms"],
      cues: [
        "Stand with feet shoulder-width apart, knees slightly bent, and core braced. Hold the medicine ball at chest height. Slightly hinge at your hips.",
        "Drive your hips forward explosively, transferring energy through your core as you press the ball forcefully from your chest toward your target.",
        "Finish in a tall standing position. You should feel the movement in your chest, shoulders, core, and hips. Avoid straining your lower back."
      ],
      balance: BalanceType.bilateral,
      balanceLevel: BalanceLevel.static,
      body: [BodyFocus.upper, BodyFocus.full],
      equipment: [Equipment.medicine_ball],
      joint: [Joint.hip, Joint.shoulder, Joint.elbow, Joint.wrist],
      lift: LiftType.compound,
      muscles: [MuscleGroup.pecs, MuscleGroup.shoulders, MuscleGroup.triceps, MuscleGroup.abs, MuscleGroup.glutes],
      pattern: [MovementPattern.hinge, MovementPattern.core, MovementPattern.push],
      plane: [MovementPlane.sagittal],
      muxPlaybackId: "h01LmuQbT3mgLVdWSLIaXfcIP7NoYP5Yo8pHP1CFMpNw",
    },
    {
      name: "Standing Medicine Ball Side Toss",
      description: "An upper body power movement that targets efficient rotation",
      tags: ["power", "plyometric", "rotation"],
      cues: [
        "Stand sideways to a wall or partner, feet shoulder-width apart, holding the medicine ball at hip height.",
        "Rotate your torso explosively as you pivot your back foot, driving the ball towards the wall or partner with power from your hips and core.",
        "Finish with your body fully rotated. You should feel this movement in your core, hips, and obliques. Avoid using just your arms.",
        "Repeat other side."
      ],
      balance: BalanceType.bilateral,
      balanceLevel: BalanceLevel.static,
      body: [BodyFocus.full],
      equipment: [Equipment.medicine_ball],
      joint: [Joint.hip, Joint.shoulder, Joint.elbow, Joint.wrist, Joint.knee, Joint.ankle],
      lift: LiftType.compound,
      muscles: [MuscleGroup.glutes, MuscleGroup.pelvic_floor, MuscleGroup.abs, MuscleGroup.obliques],
      pattern: [MovementPattern.hinge, MovementPattern.core, MovementPattern.push],
      plane: [MovementPlane.transverse],
      muxPlaybackId: "01SmwwKgzv6RNkCqQ9D01VnYS00cxd01AD5XtX5022pgh82Q",
    },
    {
      name: "Bike Conditioning",
      description: "Full body conditioning",
      tags: ["bike"],
      cues: [
        "Position the seat high enough that one leg is extended fully when pedal is at the bottom of the arc.",
        "Proceed at a steady state for time or ride at intervals",
      ],
      body: [BodyFocus.full],
      equipment: [Equipment.bike],
      joint: [Joint.hip, Joint.shoulder, Joint.elbow, Joint.wrist, Joint.knee, Joint.ankle],
      pattern: [MovementPattern.locomotive],
      plane: [MovementPlane.sagittal],
      muxPlaybackId: "43ECbGKiNUdiLf3TTuRCRBAqmCgQOdcYH6GQaB66g9g",
    },
    {
      name: "Box Jumps",
      description: "An explosive lower body exercise",
      tags: ["power", "jumping", "explosive"],
      cues: [
        "Stand in front of a box with your feet hip-width apart and knees slightly bent. Keep your core engaged and arms at your sides.",
        "Perform a quick dip with your hips and jump explosively onto the box, swinging your arms forward for momentum.",
        "Land softly with both feet on the box, absorbing the impact through your legs. You should feel the power in your legs, glutes, and core. Step down carefully."
      ],
      balance: BalanceType.bilateral,
      body: [BodyFocus.lower, BodyFocus.core, BodyFocus.full],
      equipment: [Equipment.bodyweight, Equipment.plyo_box],
      joint: [Joint.hip, Joint.knee, Joint.ankle],
      lift: LiftType.compound,
      muscles: [MuscleGroup.glutes, MuscleGroup.hamstrings, MuscleGroup.quads, MuscleGroup.adductors, MuscleGroup.abductors, MuscleGroup.erectors, MuscleGroup.pelvic_floor, MuscleGroup.hip_flexors, MuscleGroup.abs],
      pattern: [MovementPattern.squat, MovementPattern.core],
      plane: [MovementPlane.sagittal],
      muxPlaybackId: "02avXkiqQduLZs002VXCTWyXUNv9KwcLDzGT9i001bpt2c"
    },
    {
      name: "Supine Breathing",
      description: "The foundation of all movement is proper breathing technique. Proper breathing stabilizes the spine and helps prevent injury as we move through space.",
      tags: ["functional", "breathing"],
      cues: [
        "Lie on your back with your knees bent and feet flat on the floor, about hip-width apart. Rest your arms comfortably by your sides, palms facing up. Make sure your head, shoulders, and pelvis are aligned. If needed, place a small pad under your head for support. Keep your lower back in a neutral position, with a slight natural curve.",
        "Breathe deeply through your nose, allowing your ribcage to expand in all directions (outward, to the sides, and back) as you fill your lungs with air. Focus on breathing into your belly, letting it rise as you inhale. Avoid excessive chest or shoulder movement. As you exhale through your mouth, gently engage your core and let your ribcage relax back down toward the floor.",
        "Complete each breath with a full exhale, feeling your ribcage soften and your core gently engage. You should feel relaxed but stable, with the breath filling your belly and sides more than your chest. The goal is to feel expansion in the lower ribcage, diaphragm, and abdominal area. Avoid tension in your neck or shoulders."
      ],
      body: [BodyFocus.core],
      equipment: [Equipment.bodyweight],
      muscles: [MuscleGroup.erectors, MuscleGroup.abs, MuscleGroup.obliques],
      pattern: [MovementPattern.core],
      muxPlaybackId: "V7Dn1nXOTZ8EpkXguAY5ts00ZbKaKDKT02MngV2GwYK2o"
    },
    {
      name: "Calves Foam Roll",
      description: "A lower body myofascial release technique",
      tags: ["functional", "foam rolling", "calves"],
      cues: [
        "Sit on the floor with your legs extended in front of you. Place a foam roller under one calf, just above the ankle. Support yourself with your hands behind you, keeping your hips slightly off the ground. You can cross the opposite leg over the one you are rolling for added pressure or keep it flat on the ground for less intensity.",
        "Using your hands for support, slowly roll the foam roller up your calf, from the ankle to just below the knee. Move in small, controlled motions. When you find a tender spot, pause and hold for a few seconds or gently rock back and forth on it to release tension.",
        "Continue rolling for about 30 seconds to 1 minute per calf, focusing on areas of tightness or discomfort. You should feel the muscles relaxing as you work through any knots. The pressure should feel like it's working into the muscle without causing sharp pain. You should feel relief and increased mobility in your calves after rolling. Avoid rolling directly over the knee joint or applying excessive pressure.",
        "Repeat with opposite leg."
      ],
      body: [BodyFocus.lower],
      equipment: [Equipment.bodyweight, Equipment.foam_roller],
      joint: [Joint.knee, Joint.ankle],
      muscles: [MuscleGroup.calves],
      muxPlaybackId: "rFdQoRqApDggajrJow9I5k00M029hrefKh7VVMbBHM1WE",
    },
    {
      name: "Dumbbell Bench Press",
      description: "An upper body strength exercise that targets chest",
      tags: ["chest", "bench"],
      cues: [
        "Lie flat on a bench with a dumbbell in each hand. Your feet should be flat on the ground, directly under your knees, and your back slightly arched with your shoulder blades squeezed together. Hold the dumbbells at chest level, with your elbows bent at about a 45-degree angle from your body. Palms should face forward.",
        "Press the dumbbells upward by extending your arms straight, keeping control throughout the movement. Your wrists should stay neutral (not bent), and the weights should move in a smooth arc. Avoid flaring your elbows out too wide or letting them collapse inward. As you lower the dumbbells, bring them down to just outside your chest, maintaining tension in your chest and arms.",
        "Finish the movement with your arms fully extended, but don't lock out your elbows. You should feel the tension in your chest, shoulders, and triceps. Focus on maintaining control through the whole range of motion, avoiding excessive arching of your back or shrugging of your shoulders. You should feel a solid contraction in your chest and a stable base through your feet and core."
      ],
      balance: BalanceType.bilateral,
      balanceLevel: BalanceLevel.static,
      body: [BodyFocus.upper],
      contraction: ContractionType.isotonic,
      equipment: [Equipment.dumbbell, Equipment.bench],
      joint: [Joint.shoulder, Joint.elbow, Joint.wrist],
      lift: LiftType.compound,
      muscles: [MuscleGroup.pecs, MuscleGroup.triceps, MuscleGroup.shoulders],
      pattern: [MovementPattern.push],
      plane: [MovementPlane.sagittal],
      muxPlaybackId: "J01ugm7CbJuuP9uBXu2DIkKKAXbnhY4gKgaOseP00ccKc",
    },
    {
      name: "Incline Dumbbell Bench Press",
      description: "An upper body strength exercise that targets chest",
      tags: ["chest", "bench", "incline"],
      cues: [
        "Set an adjustable bench to a 30 degree incline. Sit on the bench with a dumbbell in each hand, resting them on your thighs. Lean back and plant your feet firmly on the ground, about hip-width apart. Press the dumbbells up to chest level as you lie back, with your palms facing forward and elbows bent at a 45-degree angle. Your shoulder blades should be squeezed together and your lower back slightly arched for support.",
        "Press the dumbbells upward by extending your arms straight, keeping control throughout the movement. The weights should move in a slight arc, not straight up and down. As you press, keep your wrists neutral and maintain the 45-degree elbow angle. Lower the dumbbells slowly to chest height, just outside your shoulders, while keeping tension in your chest and avoiding excessive flaring of your elbows.",
        "Finish with your arms fully extended but not locked out, and feel the contraction in your upper chest, shoulders, and triceps. You should feel the majority of the work in the upper chest due to the incline, with a strong base through your core and legs. Avoid shrugging your shoulders or allowing your back to excessively arch. Maintain control through the entire range of motion, focusing on a smooth, powerful press and a controlled descent."
      ],
      balance: BalanceType.bilateral,
      balanceLevel: BalanceLevel.static,
      body: [BodyFocus.upper],
      contraction: ContractionType.isotonic,
      equipment: [Equipment.dumbbell, Equipment.bench],
      joint: [Joint.shoulder, Joint.elbow, Joint.wrist],
      lift: LiftType.compound,
      muscles: [MuscleGroup.pecs, MuscleGroup.triceps, MuscleGroup.shoulders],
      pattern: [MovementPattern.push],
      plane: [MovementPlane.sagittal],
      muxPlaybackId: "BZ3n1EIPqDDY5FXE9psTpZCerOLA2cmQhCPRa5jBGUE",
    },
    {
      name: "Dumbbell Row",
      description: "An upper body strength exercise that targets back",
      tags: ["back"],
      cues: [
        "Set up next to a flat bench. Place one hand on the bench, with both feet planted firmly on the ground for balance. Keep your torso parallel to the ground and your back flat, with your head in a neutral position (in line with your spine). Hold a dumbbell in the opposite hand, allowing it to hang straight down from your shoulder.",
        "Pull the dumbbell up toward your ribcage by driving your elbow back, keeping it close to your body. Focus on squeezing your shoulder blades together as you row, avoiding any twisting or rotating of your torso. Your wrist should stay neutral, and your elbow should pass just behind your torso at the top of the movement.",
        "Lower the dumbbell slowly and with control, returning to the starting position with the dumbbell fully extended. You should feel the exercise primarily in your upper back, lats, and core, with a focus on stabilizing against rotation. The movement should feel controlled and smooth, and you should avoid using momentum or allowing your torso to shift. Maintain a tight core throughout to prevent twisting.",
        "Repeat with opposite arm."
      ],
      balance: BalanceType.unilateral,
      balanceLevel: BalanceLevel.static,
      body: [BodyFocus.upper],
      contraction: ContractionType.isotonic,
      equipment: [Equipment.dumbbell, Equipment.bench],
      joint: [Joint.shoulder, Joint.elbow, Joint.wrist],
      lift: LiftType.compound,
      muscles: [MuscleGroup.lats, MuscleGroup.biceps, MuscleGroup.shoulders, MuscleGroup.obliques],
      pattern: [MovementPattern.pull],
      plane: [MovementPlane.sagittal],
      muxPlaybackId: "V1Q61nd6e02J1cmsdt3lOBWTKH01itbcxvzjEbvqayIQQ",
    },
    {
      name: "Floorslide/Wallslide",
      description: "An upper body mobility drill that assesses readiness for overhead pressing motions",
      tags: ["mobility", "shoulders"],
      cues: [
        "Lie flat on your back on the floor with your knees bent and feet flat on the ground. Your lower back should be in a neutral position, gently pressed into the floor. Position your arms in a \"W\" shape, with elbows bent at 90 degrees and resting on the floor, palms facing up. Your forearms should be vertical, and your upper arms should be at shoulder level.",
        "Press your arms up into a \"Y\" shape by sliding them along the floor, extending your arms overhead while keeping your forearms, elbows, and hands in contact with the ground. As you press, focus on moving your shoulder blades upward and maintaining contact with the floor. Avoid arching your lower back or letting your ribs flare out.",
        "Fully extend your arms into the \"Y\" position, then slowly slide them back down to the \"W\" position. You should feel a stretch and engagement in your shoulders, upper back, and chest. The goal is to mobilize the shoulders and strengthen the upper back while maintaining core stability. You should feel the movement in your shoulder blades and upper back, avoiding any strain in your neck or lower back."
      ],
      body: [BodyFocus.upper],
      equipment: [Equipment.bodyweight],
      joint: [Joint.shoulder, Joint.elbow],
      pattern: [MovementPattern.push],
      plane: [MovementPlane.frontal],
      stretch: StretchType.dynamic,
      muxPlaybackId: "NXwfuEWW3QL1xqXC97b87xVhyAcoWCuikh971VbWXK8",
    },
    {
      name: "Front Plank",
      description: "A full body core stability exercise",
      tags: ["stability", "core"],
      cues: [
        "Place your forearms on the ground, with your elbows directly underneath your shoulders and your hands flat or in a fist. Extend your legs straight back, with your toes tucked under and your feet about hip-width apart. Engage your core and press the ground away with your forearms and toes. Your body should form a straight line from head to heels.",
        "Hold the plank position by keeping your core tight, pulling your belly button toward your spine. Engage your glutes and quads to help maintain a strong, stable position. Keep your neck neutral by looking slightly forward or down at the floor—avoid looking up or dropping your head. Resist any sagging in your lower back or hips.",
        "Maintain the position for the desired time, focusing on feeling the tension in your core, glutes, and shoulders. You should feel a strong contraction in your abs and some tension in your legs and arms for stabilization. Avoid feeling the strain in your lower back—if you do, reset your form by tightening your core and glutes. The goal is a solid, strong plank without any dips or rises in your hips."
      ],
      balance: BalanceType.bilateral,
      balanceLevel: BalanceLevel.static,
      body: [BodyFocus.full],
      contraction: ContractionType.isometric,
      equipment: [Equipment.bodyweight],
      joint: [Joint.ankle, Joint.hip, Joint.shoulder],
      muscles: [MuscleGroup.abs, MuscleGroup.glutes, MuscleGroup.erectors, MuscleGroup.serratus],
      pattern: [MovementPattern.core],
      plane: [MovementPlane.sagittal],
      muxPlaybackId: "Mjj9s00w01WexyvKV1Aia5IMmcXxWSn1WQzGjbBrF7kow",
    },
    {
      name: "Hip Lift / Glute Bridge",
      description: "A glute and core activation exercise",
      tags: ["stability", "core", "glutes"],
      cues: [
        "Lie on your back with your knees bent and feet flat on the floor, hip-width apart. Your heels should be close to your glutes, about 6 inches from your butt. Rest your arms by your sides, palms facing down. Ensure your head, shoulders, and hips are aligned, with your spine in a neutral position.",
        "Press through your heels and lift your hips toward the ceiling by squeezing your glutes. Your body should form a straight line from your knees to your shoulders at the top of the movement. Avoid arching your lower back or pushing through your toes—focus on lifting through your glutes and hips. Keep your core engaged to maintain stability.",
        "At the top of the lift, squeeze your glutes and hold for a brief moment. You should feel the exercise primarily in your glutes, hamstrings, and core, not in your lower back. Lower your hips back to the ground slowly and with control. Make sure to maintain tension in your glutes and core throughout the entire movement, avoiding any collapse in your hips."
      ],
      balance: BalanceType.bilateral,
      balanceLevel: BalanceLevel.static,
      body: [BodyFocus.lower],
      contraction: ContractionType.isometric,
      equipment: [Equipment.bodyweight],
      joint: [Joint.ankle, Joint.knee, Joint.hip],
      lift: LiftType.isolation,
      muscles: [MuscleGroup.glutes, MuscleGroup.hamstrings],
      pattern: [MovementPattern.hinge],
      plane: [MovementPlane.sagittal],
      muxPlaybackId: "afK1OG5pBpn02mYeC5W5YMQKFeeFPzgd8gxGYbtmj7s4",
    },
    {
      name: "Glute Foam Roll",
      description: "A lower body myofascial release technique",
      tags: ["functional", "glutes", "foam rolling"],
      cues: [
        "Sit on the foam roller, placing it under one glute. Cross the same-side leg over the opposite knee in a figure-four position to increase the intensity, while keeping the other foot flat on the floor for stability. Lean slightly toward the glute you're targeting, using your hands behind you for support.",
        "Slowly roll back and forth over the foam roller, starting from the top of the glute near the hip bone and moving down toward the base of the glute where it meets the hamstring. Use small, controlled movements and pause on any areas of tightness or tenderness. You can also rotate slightly side to side to target different areas of the glute.",
        "Continue rolling for about 15 seconds per glute. You should feel a release of tension and increased blood flow in the glute muscle. The sensation should be firm but not painful. If you find tight spots, spend extra time working them out, but avoid rolling over joints or causing excessive discomfort. You should feel looser and more mobile in your hips and glutes after rolling."
      ],
      body: [BodyFocus.lower],
      equipment: [Equipment.bodyweight, Equipment.foam_roller],
      joint: [Joint.hip],
      muscles: [MuscleGroup.glutes],
      muxPlaybackId: "Cw5cmTFxPI01b3JnpKoJfqC5zbMHFswUhiw9RRiRwYFc",
    },
    {
      name: "Half Kneeling Cable Inline Row",
      description: "An upper body pulling exercise that incorporates rotational stability",
      tags: ["functional", "stability", "cables"],
      cues: [
        "Set a cable machine at a low to mid-height with a single handle attachment. Get into a half-kneeling position facing the machine, with the knee of your inside leg (the leg closest to the machine) down and the opposite foot flat on the floor in front of you. Your hips and shoulders should be square, and your torso upright. Hold the cable handle with the opposite (outside) hand, with your arm fully extended in front of you. Keep your core engaged to maintain stability.",
        "Row the handle straight back toward your ribcage by pulling through your elbow and squeezing your shoulder blade toward your spine. Keep your torso stable and avoid rotating or leaning back as you row. Focus on driving the movement from your upper back and shoulder, keeping your elbow close to your body. Maintain a neutral wrist and controlled movement.",
        "Finish with your elbow just past your torso, feeling a strong contraction in your mid-back and lats. Slowly return the handle to the starting position, keeping tension in your back and core. You should feel this exercise primarily in your upper back and lats, with your core engaged to prevent rotation. Maintain control throughout the movement and avoid using momentum or letting your hips shift.",
        "Repeat with opposite arm."
      ],
      balance: BalanceType.unilateral,
      balanceLevel: BalanceLevel.static,
      body: [BodyFocus.upper, BodyFocus.core],
      contraction: ContractionType.isotonic,
      equipment: [Equipment.cable_machine],
      joint: [Joint.shoulder, Joint.elbow],
      lift: LiftType.compound,
      muscles: [MuscleGroup.lats, MuscleGroup.biceps, MuscleGroup.obliques],
      pattern: [MovementPattern.pull, MovementPattern.lunge, MovementPattern.core],
      plane: [MovementPlane.sagittal, MovementPlane.transverse],
      muxPlaybackId: "rzI8edfeiH3kFAKcaqJOvezk1Z02fQapq1DvcfDQuAFI",
    },
    {
      name: "Hamstrings Foam Roll",
      description: "A lower body myofascial release technique",
      tags: ["functional", "hamstrings", "foam rolling"],
      cues: [
        "Sit on the floor with your legs extended in front of you. Place the foam roller under one hamstring, just above the back of your knee. Use your hands placed behind you on the floor for support, keeping your arms straight. You can either keep the opposite leg flat on the floor for lighter pressure or cross it over the leg you're rolling for added intensity.",
        "Slowly roll up and down along the length of your hamstring, from just above the knee to just below the glute. Move in controlled, small motions, focusing on areas of tightness or discomfort. You can rotate your leg slightly inward and outward to target different parts of the hamstring. Pause and hold on any tight spots for a few seconds, and gently rock back and forth to release tension.",
        "Continue rolling for about 15 seconds per hamstring, focusing on relaxing the muscle and releasing any knots or tight spots. You should feel a gradual loosening of the hamstring muscle, with pressure that feels firm but not painful. Avoid applying too much pressure directly on the knee joint. After foam rolling, your hamstrings should feel more mobile and less tight.",
      ],
      body: [BodyFocus.lower],
      equipment: [Equipment.bodyweight, Equipment.foam_roller],
      joint: [Joint.hip, Joint.knee],
      muscles: [MuscleGroup.hamstrings],
      muxPlaybackId: "Y13TPfdmBJfGuTMMiSfGGb9jSYJTw8fKs01YryBsPgYs",
    },
    {
      name: "Hip Flexor Foam Roll",
      description: "A lower body myofascial release technique",
      tags: ["functional", "hip flexors", "foam rolling"],
      cues: [
        "Lie face down on the floor and place the foam roller under one hip flexor, just below the hip bone at the front of your pelvis. Support yourself on your forearms, and use your opposite leg for balance by bending it out to the side or keeping it extended behind you. Your other leg (the one being rolled) should remain straight and relaxed.",
        "Slowly roll the foam roller up and down the front of your hip, from just below the hip bone to about midway down the thigh. Move in small, controlled motions and focus on any tight or tender spots. You can rotate slightly inward or outward to target different parts of the hip flexor. Pause and hold on any areas of discomfort, or gently rock back and forth to help release tension.",
        "Continue rolling for about 15 seconds on each side, feeling the muscle loosen and relax. You should feel the pressure in your hip flexor and the top of your thigh, but avoid causing sharp pain or rolling directly over the bones of your pelvis. After foam rolling, you should feel increased mobility and reduced tightness in the hip flexors, allowing for better hip extension and overall movement.",
      ],
      body: [BodyFocus.lower],
      equipment: [Equipment.bodyweight, Equipment.foam_roller],
      joint: [Joint.hip],
      muscles: [MuscleGroup.hip_flexors],
      muxPlaybackId: "eVXOea01MfF3J4Zt1wGzu7y1uJy01byZO7NMnMIaYBy6I",
    },
    {
      name: "Kettlebell Deadlift",
      description: "A lower body hinge exercise that translates to many athletic movements",
      tags: ["functional", "strength", "glutes", "back"],
      cues: [
        "Stand with your feet hip-width apart, toes pointing slightly outward. Place a kettlebell on the floor between your feet, aligned with your midfoot. Hinge at your hips by pushing them back while maintaining a slight bend in your knees. Keep your back flat, chest up, and core engaged. Reach down and grab the kettlebell with both hands, keeping your arms straight and shoulders pulled back.",
        "Create tension by \"breaking\" the bar. Push the ground away by driving through the arches of the feet and come to a standing position. Your shoulders, hips, and knees should all extend together in one smooth motion. Avoid arching your lower back through the movement.",
        "Finish with your glutes engaged and core tight, feeling a strong contraction in your mid-back and lats. Slowly hinge the hips back and lower the kettlebell to the starting position, keeping tension in your back and core. You should feel this exercise primarily in your hamstrings, glutes, and lats, with your core engaged to prevent back arching.",
      ],
      balance: BalanceType.bilateral,
      balanceLevel: BalanceLevel.static,
      body: [BodyFocus.full, BodyFocus.lower],
      contraction: ContractionType.isotonic,
      equipment: [Equipment.kettlebell],
      joint: [Joint.ankle, Joint.knee, Joint.hip, Joint.shoulder],
      lift: LiftType.compound,
      muscles: [MuscleGroup.lats, MuscleGroup.glutes, MuscleGroup.hamstrings, MuscleGroup.erectors, MuscleGroup.abductors, MuscleGroup.adductors, MuscleGroup.pelvic_floor],
      pattern: [MovementPattern.pull, MovementPattern.hinge, MovementPattern.core],
      plane: [MovementPlane.sagittal],
      muxPlaybackId: "mCd01PET6JsK1Fj00N0000xxFaoMR3oAjYPPuLX02FxlbI2U",
    },
    {
      name: "Farmers Carry",
      description: "A core stabilizing exercise",
      tags: ["functional", "stabilizer", "core"],
      cues: [
        "Stand tall with your feet hip-width apart, holding a dumbbell or kettlebell in each hand at your sides. Your palms should face in toward your body, with your arms fully extended but not locked out. Pull your shoulders down and back, engage your core, and keep your chest up. Ensure that your posture is strong and upright.",
        "Begin walking forward, taking small, controlled steps. Keep your core tight and your posture tall, with your shoulders stable and your arms straight by your sides. Avoid leaning or letting the kettlebells pull you to one side. Focus on maintaining balance and control as you walk. Keep your steps smooth and deliberate, moving with purpose.",
        "Continue walking for the desired distance or time, then carefully set the weights down by hinging at the hips. You should feel the exercise in your forearms, shoulders, upper back, core, and legs. The key areas of focus are grip strength, core stability, and maintaining good posture throughout the carry. Avoid slouching or letting the weights cause your body to shift or sway."
      ],
      balance: BalanceType.bilateral,
      balanceLevel: BalanceLevel.dynamic,
      body: [BodyFocus.full, BodyFocus.core],
      contraction: ContractionType.isometric,
      equipment: [Equipment.kettlebell, Equipment.dumbbell],
      joint: [Joint.hip, Joint.shoulder],
      muscles: [MuscleGroup.traps, MuscleGroup.erectors, MuscleGroup.obliques, MuscleGroup.abs],
      pattern: [MovementPattern.core, MovementPattern.locomotive],
      plane: [MovementPlane.frontal, MovementPlane.sagittal],
      muxPlaybackId: "a5hSUwmp00rvp1MxVhxP009QGw500DpYDwKZ5th31Nsij4",
    },
    {
      name: "Goblet Squat",
      description: "A lower body squat exercise that translates to many athletic movements",
      tags: ["functional", "strength", "squat"],
      cues: [
        "Hold a kettlebell or dumbbell with both hands at chest height, gripping the weight firmly by the sides. Your elbows should be close to your body. Stand with your feet slightly wider than hip-width apart, with your toes pointed slightly outward. Keep your chest up, core engaged, and shoulders pulled back.",
        "Begin the squat by pushing your hips back and bending your knees, lowering your body as if sitting into a chair. Keep your chest up and your weight distributed evenly through your feet, focusing on pressing through your heels. Your knees should track in line with your toes, not caving inward. Lower yourself until your thighs are at least parallel to the ground or slightly below, maintaining control throughout.",
        "Drive through your heels to stand back up, extending your knees and hips fully while keeping the goblet position stable. You should feel the exercise primarily in your quads, glutes, and core. Keep your chest tall and avoid rounding your back as you rise. You should feel balanced and controlled throughout the movement, avoiding any shifting of weight onto your toes.",
      ],
      balance: BalanceType.bilateral,
      balanceLevel: BalanceLevel.static,
      body: [BodyFocus.full, BodyFocus.lower],
      contraction: ContractionType.isotonic,
      equipment: [Equipment.kettlebell, Equipment.dumbbell],
      joint: [Joint.ankle, Joint.knee, Joint.hip],
      lift: LiftType.compound,
      muscles: [MuscleGroup.glutes, MuscleGroup.hamstrings, MuscleGroup.quads, MuscleGroup.adductors, MuscleGroup.abductors, MuscleGroup.erectors, MuscleGroup.hip_flexors, MuscleGroup.pelvic_floor],
      pattern: [MovementPattern.squat],
      plane: [MovementPlane.sagittal, MovementPlane.frontal],
      muxPlaybackId: "ieS02o8ylL00mb23Yu15II968S675LKwD7xzjBTfw3wOo",
    },
    {
      name: "Single Leg Deadlift",
      description: "A lower body hinge exercise that improves balance and core strength",
      tags: ["functional", "strength", "hinge", "balance"],
      cues: [
        "Hold a kettlebell or dumbbell against your chest in the goblet position, with both hands gripping the weight and your elbows tucked in. Step into a split stance, with one foot forward and the other foot behind you, about shoulder-width apart. Your front foot should be flat on the ground, and your back heel should be off the floor. Keep your torso upright, core braced, and shoulders back.",
        "Lower your body by bending both knees, allowing your back knee to move toward the floor. Keep your front knee in line with your toes, avoiding letting it cave inward. As you descend, your back knee should come close to the floor without touching it, and your torso should remain upright. Focus on driving through the arch of your front foot.",
        "Press through the arch of your front foot to return to the starting position, fully extending your front leg while keeping the goblet position stable. You should feel the movement primarily in your quads, glutes, and hamstrings of the front leg. Your core should remain engaged to support balance and stability. Avoid letting your back round or your hips shift to one side. Switch legs and repeat for the desired reps.",
        "Repeat with opposite leg.",
      ],
      balance: BalanceType.unilateral,
      balanceLevel: BalanceLevel.dynamic,
      body: [BodyFocus.full, BodyFocus.lower],
      contraction: ContractionType.isotonic,
      equipment: [Equipment.kettlebell, Equipment.dumbbell],
      joint: [Joint.ankle, Joint.knee, Joint.hip, Joint.shoulder],
      lift: LiftType.compound,
      muscles: [MuscleGroup.glutes, MuscleGroup.hamstrings, MuscleGroup.quads, MuscleGroup.adductors, MuscleGroup.abductors, MuscleGroup.erectors],
      pattern: [MovementPattern.hinge, MovementPattern.rotational],
      plane: [MovementPlane.sagittal, MovementPlane.frontal, MovementPlane.transverse],
      muxPlaybackId: "c00bf1cS7eQiIsBc9SYuQVbcG9valcRgaSBp8KeNj009c",
    },
    {
      name: "Goblet Split Squat",
      description: "A lower body squat exercise that translates to many locomotive movements",
      tags: ["functional", "strength", "lunges"],
      cues: [
        "Hold a kettlebell or dumbbell against your chest in the goblet position, with both hands gripping the weight and your elbows tucked in. Step into a split stance, with one foot forward and the other foot behind you, about shoulder-width apart. Your front foot should be flat on the ground, and your back heel should be off the floor. Keep your torso upright, core braced, and shoulders back.",
        "Lower your body by bending both knees, allowing your back knee to move toward the floor. Keep your front knee in line with your toes, avoiding letting it cave inward. As you descend, your back knee should come close to the floor without touching it, and your torso should remain upright. Focus on driving through the arch of your front foot.",
        "Press through the arch of your front foot to return to the starting position, fully extending your front leg while keeping the goblet position stable. You should feel the movement primarily in your quads, glutes, and hamstrings of the front leg. Your core should remain engaged to support balance and stability. Avoid letting your back round or your hips shift to one side. Switch legs and repeat for the desired reps.",
      ],
      balance: BalanceType.unilateral,
      balanceLevel: BalanceLevel.static,
      body: [BodyFocus.full, BodyFocus.lower],
      contraction: ContractionType.isotonic,
      equipment: [Equipment.kettlebell, Equipment.dumbbell],
      joint: [Joint.ankle, Joint.knee, Joint.hip],
      lift: LiftType.compound,
      muscles: [MuscleGroup.glutes, MuscleGroup.hamstrings, MuscleGroup.quads, MuscleGroup.adductors, MuscleGroup.abductors, MuscleGroup.erectors],
      pattern: [MovementPattern.lunge, MovementPattern.squat],
      plane: [MovementPlane.sagittal, MovementPlane.frontal],
      muxPlaybackId: "s628Twytob5ynbDKqKoNMiLHvMG2ZyTauK02vuV5texM",
    },
    {
      name: "Suitcase Carry",
      description: "A core stabilizing exercise",
      tags: ["functional", "stabilizer", "core"],
      cues: [
        "Stand tall with your feet hip-width apart, holding a dumbbell or kettlebell in one hand by your side as if carrying a suitcase. Your arm should be fully extended, and the kettlebell should be close to your hip. Keep your shoulders level, avoiding any leaning or dropping to the side. Engage your core to maintain stability and balance.",
        "Begin walking forward, taking controlled and deliberate steps. Keep your posture upright and your core tight to resist the urge to lean to the side. Your shoulders should remain level, and the kettlebell should stay stable by your side, with minimal swinging. Focus on maintaining balance and a steady pace.",
        "Walk for the desired distance or time, then carefully set the kettlebell down by hinging at your hips. You should feel the exercise primarily in your core (especially the obliques), as well as in your grip, shoulders, and legs. The goal is to maintain an upright posture and avoid leaning toward the weight. After completing one side, switch hands and repeat the carry on the other side to ensure balanced strength development.",
      ],
      balance: BalanceType.bilateral,
      balanceLevel: BalanceLevel.dynamic,
      body: [BodyFocus.full, BodyFocus.core],
      contraction: ContractionType.isometric,
      equipment: [Equipment.kettlebell, Equipment.dumbbell],
      joint: [Joint.hip, Joint.shoulder],
      muscles: [MuscleGroup.traps, MuscleGroup.erectors, MuscleGroup.obliques, MuscleGroup.abs],
      pattern: [MovementPattern.core, MovementPattern.locomotive],
      plane: [MovementPlane.frontal, MovementPlane.sagittal],
      muxPlaybackId: "G02qub2Qj013kbp44UaNK2WdSBDqdOGTA01Wu01ipBPBHRI",
    },
    {
      name: "Knee to Chest Walk",
      description: "A locomotive dynamic stretch",
      tags: ["functional", "stabilizer", "balance"],
      cues: [
        "Stand tall with your feet hip-width apart, holding a dumbbell or kettlebell in one hand by your side as if carrying a suitcase. Your arm should be fully extended, and the kettlebell should be close to your hip. Keep your shoulders level, avoiding any leaning or dropping to the side. Engage your core to maintain stability and balance.",
        "Begin walking forward, taking controlled and deliberate steps. Keep your posture upright and your core tight to resist the urge to lean to the side. Your shoulders should remain level, and the kettlebell should stay stable by your side, with minimal swinging. Focus on maintaining balance and a steady pace.",
        "Walk for the desired distance or time, then carefully set the kettlebell down by hinging at your hips. You should feel the exercise primarily in your core (especially the obliques), as well as in your grip, shoulders, and legs. The goal is to maintain an upright posture and avoid leaning toward the weight. After completing one side, switch hands and repeat the carry on the other side to ensure balanced strength development.",
      ],
      balance: BalanceType.unilateral,
      balanceLevel: BalanceLevel.dynamic,
      body: [BodyFocus.full, BodyFocus.lower],
      contraction: ContractionType.isometric,
      equipment: [Equipment.bodyweight],
      joint: [Joint.hip, Joint.ankle],
      muscles: [MuscleGroup.glutes, MuscleGroup.hip_flexors],
      pattern: [MovementPattern.locomotive],
      plane: [MovementPlane.frontal, MovementPlane.sagittal],
      stretch: StretchType.dynamic,
      muxPlaybackId: "JZaigadq02A3tlHu1o01dpfM2t52dGdkc01P003iu013FfEE",
    },
    {
      name: "Lateral Bound",
      description: "An explosive lower body exercise that improves balance",
      tags: ["functional", "explosive", "lunges", "athletic"],
      cues: [
        "Stand tall with your feet hip-width apart, knees slightly bent, and your core engaged. Shift your weight onto one leg, with the other foot slightly off the ground. Bend your knees and hips slightly to load the leg you're standing on, preparing for the jump. Your arms should be in front of you, ready to swing for momentum.",
        "Push off explosively from the leg you're standing on, jumping sideways (laterally) to land on the opposite leg. As you bound, swing your arms for additional momentum, and keep your core engaged to control the movement. Land softly on the opposite leg, bending your knee and hip to absorb the impact. Maintain balance by keeping your chest up and avoiding leaning too far forward or back.",
        "Stabilize yourself upon landing, balancing on the landing leg before quickly bounding back in the other direction. You should feel this exercise in your glutes, quads, hamstrings, and core, as well as in the stabilizing muscles around your ankles and hips. Focus on maintaining balance and control with each bound, making sure your knee stays in line with your toes to avoid inward collapsing. Repeat for the desired number of reps or time, alternating sides with each bound.",
      ],
      balance: BalanceType.unilateral,
      balanceLevel: BalanceLevel.dynamic,
      body: [BodyFocus.full, BodyFocus.lower],
      contraction: ContractionType.isotonic,
      equipment: [Equipment.bodyweight],
      joint: [Joint.ankle, Joint.knee, Joint.hip],
      lift: LiftType.compound,
      muscles: [MuscleGroup.glutes, MuscleGroup.hamstrings, MuscleGroup.quads, MuscleGroup.adductors, MuscleGroup.abductors],
      pattern: [MovementPattern.lunge, MovementPattern.squat],
      plane: [MovementPlane.frontal],
      muxPlaybackId: "EMkDMJBy8ByKJJgXdCV7zHn8BIJ7OcxtKA00nRar7tjk",
    },
    {
      name: "Lateral Lunge",
      description: "An lower body exercise that improves balance",
      tags: ["functional", "lunges", "balance"],
      cues: [
        "Stand tall with your feet together and your core engaged. Keep your chest up, shoulders back, and arms relaxed at your sides or in front of you for balance. Your toes should point forward.",
        "Take a big step to the side with one leg, keeping your toes pointing forward and both feet flat on the ground. As you step out, bend the knee of the stepping leg and push your hips back, lowering your body into a lunge position. Your opposite leg should remain straight, with your foot flat on the floor. Keep your chest up and your back flat, avoiding rounding your spine. Ensure your knee tracks over your toes, not caving inward.",
        "Push off the bent leg to return to the starting position, bringing your feet back together. You should feel the stretch in the inner thigh of your straight leg, and the work in your glutes, quads, and hamstrings of the lunging leg. Avoid shifting your weight too far forward or allowing your back to round. Repeat on the opposite side for the desired number of reps or sets.",
      ],
      balance: BalanceType.unilateral,
      balanceLevel: BalanceLevel.static,
      body: [BodyFocus.lower],
      contraction: ContractionType.isotonic,
      equipment: [Equipment.bodyweight],
      joint: [Joint.ankle, Joint.knee, Joint.hip],
      lift: LiftType.compound,
      muscles: [MuscleGroup.glutes, MuscleGroup.hamstrings, MuscleGroup.quads, MuscleGroup.adductors, MuscleGroup.abductors],
      pattern: [MovementPattern.lunge, MovementPattern.squat],
      plane: [MovementPlane.frontal],
      muxPlaybackId: "AlWsecKmWNVgzMQs47AahMUffH5O9yczvcv015FqsFZo"
    },
    {
      name: "Leg Cradle Walk",
      description: "A locomotive dynamic stretch",
      tags: ["functional", "stabilizer", "balance"],
      cues: [
        "Stand tall with your feet hip-width apart, core engaged, and chest up. Relax your arms by your sides, preparing for a controlled movement.",
        "Lift one leg, grabbing your shin with both hands, and gently pull your knee toward your chest while simultaneously pulling your ankle across your body toward the opposite shoulder. This will create a deep stretch in the glutes and hips. Keep your standing leg straight and maintain your balance by engaging your core and keeping your posture upright.",
        "After holding the stretch for a brief moment, release the leg and take a step forward. Repeat on the opposite leg, alternating sides as you walk forward. You should feel a stretch in your glutes, hips, and lower back with each cradle. Maintain a smooth, controlled motion throughout, avoiding any leaning or loss of balance. Continue for the desired distance or number of repetitions.",
      ],
      balance: BalanceType.unilateral,
      balanceLevel: BalanceLevel.dynamic,
      body: [BodyFocus.full, BodyFocus.lower],
      contraction: ContractionType.isometric,
      equipment: [Equipment.bodyweight],
      joint: [Joint.hip, Joint.ankle],
      muscles: [MuscleGroup.glutes, MuscleGroup.hip_flexors],
      pattern: [MovementPattern.locomotive],
      plane: [MovementPlane.frontal, MovementPlane.sagittal],
      stretch: StretchType.dynamic,
      muxPlaybackId: "KOq1C4Ja7A918fGQ2YQkRTiMSfFzwFzJWmAnQUtsVR8",
    },
    {
      name: "Mini Band ER/IR",
      description: "A lower glute activation exercise",
      tags: ["functional", "activation", "glutes"],
      cues: [
        "Place a mini band just above your knees and stand tall with your feet hip-width apart. Keep your core engaged, chest up, and shoulders back. If you need extra stability, you can place your hands on your hips or hold onto a stable object for balance.",
        "Hinge the hips back and slightly bend the knees. Drive one knee out to the side slowly stretching the band. Slowly return the knee to the start position. Repeat for the desired number of reps and switch to opposite leg to repeat",
        "Maintain a controlled movement and feel the burn and activation in the glutes.",
      ],
      balance: BalanceType.bilateral,
      balanceLevel: BalanceLevel.static,
      body: [BodyFocus.lower],
      contraction: ContractionType.isotonic,
      equipment: [Equipment.resistance_band],
      joint: [Joint.ankle, Joint.knee, Joint.hip],
      lift: LiftType.isolation,
      muscles: [MuscleGroup.glutes, MuscleGroup.adductors, MuscleGroup.abductors],
      pattern: [MovementPattern.hinge],
      plane: [MovementPlane.sagittal, MovementPlane.frontal],
      muxPlaybackId: "GZVFaJSzhPVIG400nJnqtvWG02AtUqhaU35wqq6IuuG2w",
    },
    {
      name: "Mini Band Walks",
      description: "A lower glute activation exercise",
      tags: ["functional", "activation", "glutes"],
      cues: [
        "Place a mini band just above your knees or around your ankles, depending on your desired resistance level. Stand with your feet hip-width apart, a slight bend in your knees, and your hips pushed slightly back (as if in a quarter squat). Keep your chest up, core engaged, and shoulders back.",
        "Step laterally (to the side) with one foot while maintaining tension in the mini band. Move your other foot in the same direction to return to your original stance, but do not let your feet come too close together—the goal is to maintain tension in the band throughout. Keep your hips level and avoid shifting or rocking your upper body. Take controlled, small steps to the side, maintaining the same quarter-squat position.",
        "Continue stepping in one direction for the desired number of steps, then reverse the direction and repeat. You should feel the exercise in your glutes (particularly the glute medius), outer thighs, and hips. Focus on keeping your feet pointed forward and maintaining tension in the band. Avoid letting your knees cave inward or your upper body shift excessively. Maintain a smooth, controlled motion with consistent tension on the band for the best activation.",
      ],
      balance: BalanceType.bilateral,
      balanceLevel: BalanceLevel.static,
      body: [BodyFocus.lower],
      contraction: ContractionType.isotonic,
      equipment: [Equipment.resistance_band],
      joint: [Joint.ankle, Joint.knee, Joint.hip],
      lift: LiftType.isolation,
      muscles: [MuscleGroup.glutes, MuscleGroup.adductors, MuscleGroup.abductors],
      pattern: [MovementPattern.hinge],
      plane: [MovementPlane.frontal],
      muxPlaybackId: "S8xXg01R01RxbX2H2exILoA2mhlUJRaLekbkwyznhFUyw",
    },
    {
      name: "Medicine Ball Slams",
      description: "A lower glute activation exercise",
      tags: ["functional", "activation", "glutes"],
      cues: [
        "Stand with your feet shoulder-width apart, holding a medicine ball with both hands at chest height. Engage your core, and keep your chest up and shoulders back. Slightly bend your knees, preparing to generate power through your entire body.",
        "Lift the medicine ball overhead with extended arms, rising slightly onto your toes to fully extend your body. As you bring the ball overhead, engage your core and drive your hips and shoulders down explosively, slamming the ball into the ground as hard as you can. Follow through by bending at the knees and hips, hinging forward to add power to the slam. Keep your arms straight during the slam, and focus on using your whole body—legs, core, and arms—to generate force.",
        "Catch or retrieve the ball after it bounces (if it does), and immediately reset for the next rep. You should feel this exercise in your core, shoulders, arms, and legs, with an emphasis on explosive power. Your whole body should be engaged throughout the movement. Avoid rounding your back or letting your knees collapse inward as you slam the ball. Keep your movements fast, controlled, and powerful.",
      ],
      balance: BalanceType.bilateral,
      balanceLevel: BalanceLevel.static,
      body: [BodyFocus.lower, BodyFocus.full, BodyFocus.core],
      contraction: ContractionType.isotonic,
      equipment: [Equipment.medicine_ball],
      joint: [Joint.ankle, Joint.knee, Joint.hip, Joint.shoulder],
      lift: LiftType.compound,
      muscles: [MuscleGroup.glutes, MuscleGroup.abs, MuscleGroup.lats, MuscleGroup.pelvic_floor],
      pattern: [MovementPattern.hinge, MovementPattern.core, MovementPattern.pull],
      plane: [MovementPlane.sagittal],
      muxPlaybackId: "RAQQsSCA61EIepOENElDW01gC8i9nZssUo7001UhvthmA",
    },
    {
      name: "Quadriceps Foam Roll",
      description: "A lower body myofascial release technique",
      tags: ["functional", "foam rolling", "quadriceps"],
      cues: [
        "Lie face down on the floor with a foam roller positioned under your quads, just above your knees. Support yourself on your forearms, keeping your elbows directly under your shoulders. Your legs should be extended straight behind you, with your feet lifted slightly off the ground. Engage your core to keep your body stable.",
        "Slowly roll your body forward so the foam roller moves up your quads toward your hips. Roll from just above your knees to the top of your thighs. Use your arms and upper body to control the movement, and go slowly to find any tight spots or trigger points. If you find a particularly tender spot, pause and hold for a few seconds to allow the muscle to release tension, or gently rock side to side over that area.",
        "Continue rolling for roughly 15 seconds per quad. You should feel the foam roller working into your quads, releasing tightness and increasing blood flow. Avoid rolling directly over your knee joint or applying too much pressure. You should feel a gradual loosening of the muscle, and after foam rolling, your quads should feel more flexible and less tight. Keep your movements controlled and avoid rushing through the process.",
      ],
      body: [BodyFocus.lower],
      equipment: [Equipment.bodyweight, Equipment.foam_roller],
      joint: [Joint.hip, Joint.knee],
      muscles: [MuscleGroup.quads],
      pattern: [MovementPattern.squat, MovementPattern.lunge],
      plane: [MovementPlane.frontal],
      muxPlaybackId: "QQF00WuozkKsLX8hseLcK67p5bmfnNYgqGQ6TitusMVA",
    },
    {
      name: "Reaching Lateral Lunge",
      description: "An lower body exercise that improves balance",
      tags: ["functional", "lunges", "balance"],
      cues: [
        "Hold a kettlebell, dumbbell or medicine ball against your chest in the goblet position. Stand tall with your feet together and your core engaged. Keep your chest up, shoulders back. Your toes should point forward.",
        "Take a big step to the side with one leg, keeping your toes pointing forward and both feet flat on the ground. Press the weight out in front of you as you step out and hinge the hips back. Your opposite leg should remain straight, with your foot flat on the floor. Keep your chest up and your back flat, avoiding rounding your spine or lowering the weigth. Ensure your knee tracks over your toes, not caving inward.",
        "Push off the bent leg to return to the starting position, bringing your feet back together and bringing the weight back to your chest. You should feel the stretch in the inner thigh of your straight leg, and the work in your glutes, quads, and hamstrings of the lunging leg. Avoid shifting your weight too far forward or allowing your back to round. Repeat on the opposite side for the desired number of reps or sets.",
      ],
      balance: BalanceType.unilateral,
      balanceLevel: BalanceLevel.static,
      body: [BodyFocus.lower, BodyFocus.core, BodyFocus.full],
      contraction: ContractionType.isotonic,
      equipment: [Equipment.bodyweight, Equipment.dumbbell, Equipment.medicine_ball, Equipment.kettlebell],
      joint: [Joint.ankle, Joint.knee, Joint.hip, Joint.shoulder],
      lift: LiftType.compound,
      muscles: [MuscleGroup.glutes, MuscleGroup.hamstrings, MuscleGroup.quads, MuscleGroup.adductors, MuscleGroup.abductors, MuscleGroup.erectors, MuscleGroup.shoulders],
      pattern: [MovementPattern.lunge, MovementPattern.squat, MovementPattern.push],
      plane: [MovementPlane.frontal, MovementPlane.sagittal],
      muxPlaybackId: "8HlOIpUPa2ur6pzng0102iYzBDRRWA9omKjkm10200sPPAo",
    },
    {
      name: "Reaching Single Leg Deadlift",
      description: "An lower body exercise that improves balance",
      tags: ["functional", "balance", "deadlift"],
      cues: [
        "Stand tall with your feet hip-width apart. Shift your weight to your right leg, slightly bend the knee, and extend your left leg straight behind you. Keep your core tight, shoulders back, and arms extended straight out in front of you.",
        "Begin to hinge at the hips by pushing your hips back as you reach your arms forward and extend your left leg behind you. Keep a straight line from your head to your heel as your torso lowers parallel to the floor. Maintain a soft bend in your standing leg while your back remains flat.",
        "Return to standing by driving through your right heel, engaging your glutes and hamstrings to lift your torso back up. Finish with a tall posture, shoulders pulled back, and core engaged. You should feel this in the hamstrings and glutes of the standing leg, while also feeling your core working to maintain balance. Avoid feeling strain in your lower back.",
        "Repeat with opposite leg.",
      ],
      balance: BalanceType.unilateral,
      balanceLevel: BalanceLevel.dynamic,
      body: [BodyFocus.lower, BodyFocus.core],
      contraction: ContractionType.isotonic,
      equipment: [Equipment.bodyweight],
      joint: [Joint.ankle, Joint.knee, Joint.hip, Joint.shoulder],
      lift: LiftType.compound,
      muscles: [MuscleGroup.glutes, MuscleGroup.hamstrings, MuscleGroup.quads, MuscleGroup.adductors, MuscleGroup.abductors, MuscleGroup.erectors, MuscleGroup.shoulders],
      pattern: [MovementPattern.hinge],
      plane: [MovementPlane.sagittal, MovementPlane.transverse],
      muxPlaybackId: "7BLwcXxbceIsniBtbdThz3blTZG1i2lftuOATmOu7ms",
    },
    {
      name: "Sled Push",
      description: "An lower body exercise that improves speed, power and conditioning",
      tags: ["functional", "athletic"],
      cues: [
        "Stand behind the sled with both hands gripping the handles or bars. Set your feet hip-width apart, and hinge forward at the hips, keeping your spine neutral and core braced. Your arms should be extended, and your chest close to the sled. Start with light to moderate resistance on the sled.",
        "Drive forward by pushing through the balls of your feet, keeping your hips low and maintaining a forward lean. Move in a controlled and steady motion, taking powerful strides while maintaining a straight line from your shoulders to your heels.",
        "Push the sled to the end of the designated distance. You should feel this in your quads, glutes, hamstrings, and calves. Your core will be engaged to maintain stability and alignment. Avoid rounding your back or letting your hips rise too high—keep the drive from your legs, not your back.",
      ],
      balance: BalanceType.bilateral,
      balanceLevel: BalanceLevel.static,
      body: [BodyFocus.lower],
      contraction: ContractionType.isotonic,
      equipment: [Equipment.sled],
      joint: [Joint.ankle, Joint.knee, Joint.hip],
      lift: LiftType.compound,
      muscles: [MuscleGroup.glutes, MuscleGroup.hamstrings, MuscleGroup.quads],
      pattern: [MovementPattern.locomotive, MovementPattern.lunge],
      plane: [MovementPlane.sagittal],
      muxPlaybackId: "17ZQ1BvMNv011z5hmmyC00RzPhQhn2l1EclwJUMgKoEJQ",
    },
    {
      name: "Spiderman Stretch",
      description: "An lower stretch that improves hip mobility",
      tags: ["functional", "mobility"],
      cues: [
        "Start in a high plank position with your hands directly under your shoulders and feet hip-width apart. Your body should form a straight line from your head to your heels. Engage your core and keep your back flat.",
        "Step your right foot outside of your right hand, dropping your hips down toward the floor to deepen the stretch in your hips. Keep your left leg extended straight behind you, staying on the ball of your foot. You can lower your left knee to the ground for an easier variation. As you hold the stretch, drive your right elbow outwards into the right thigh to wedge the right knee and hip open, enhancing the stretch.",
        "Hold the stretch for a few breaths, then return to the plank position and switch sides. You should feel this in your hips, inner thighs, and groin, with a stretch along your hamstrings and hip flexors. Your core should remain engaged, and avoid letting your back arch or sag during the stretch.",
      ],
      body: [BodyFocus.lower],
      contraction: ContractionType.isometric,
      equipment: [Equipment.bodyweight],
      joint: [Joint.ankle, Joint.knee, Joint.hip],
      muscles: [MuscleGroup.hamstrings, MuscleGroup.quads, MuscleGroup.abductors, MuscleGroup.adductors],
      pattern: [MovementPattern.lunge],
      plane: [MovementPlane.sagittal],
      stretch: StretchType.static,
      muxPlaybackId: "2hfDY4jzZeTRi7unQ117qNVstu89TMABMMlxe4X6mhE",
    },
    {
      name: "Split Squat Hold",
      description: "A lower body lunge exercise that improves balance and endurance",
      tags: ["functional", "balance", "lunges"],
      cues: [
        "Step into a split stance, with one foot forward and the other foot behind you, about shoulder-width apart. Your front foot should be flat on the ground, and your back heel should be off the floor. Keep your torso upright, core braced, and hands behind your head.",
        "Lower your body by bending both knees, allowing your back knee to move toward the floor. Keep your front knee in line with your toes, avoiding letting it cave inward. Pause and hold the split stance without letting your knee touch the ground. Hold the stance for the desired amount of time.",
        "Press through the arch of your front foot to return to the starting position, fully extending your front leg while keeping the goblet position stable. You should feel the movement primarily in your quads, glutes, and hamstrings of the front leg. Your core should remain engaged to support balance and stability. Avoid letting your back round or your hips shift to one side.",
        "Repeat with the opposite leg.",
      ],
      balance: BalanceType.unilateral,
      balanceLevel: BalanceLevel.static,
      body: [BodyFocus.lower],
      contraction: ContractionType.isometric,
      equipment: [Equipment.bodyweight],
      joint: [Joint.ankle, Joint.knee, Joint.hip],
      lift: LiftType.compound,
      muscles: [MuscleGroup.glutes, MuscleGroup.hamstrings, MuscleGroup.quads, MuscleGroup.adductors, MuscleGroup.abductors, MuscleGroup.erectors],
      pattern: [MovementPattern.lunge, MovementPattern.squat],
      plane: [MovementPlane.sagittal],
      muxPlaybackId: "VBGBVJn4Cq6LbhY8eDrWhHSf5TQIjzQoAh01YvdZPnbA",
    },
    {
      name: "Standing Cable Chop",
      description: "A full body core exercise that improves rotational power and stability",
      tags: ["functional", "stability", "rotation"],
      cues: [
        "Attach a handle to the cable machine at the highest setting. Stand sideways to the machine with your feet shoulder-width apart, knees slightly bent. Hold the handle with both hands, arms extended, starting near your shoulder closest to the machine. Engage your core, and make sure your hips and shoulders are squared, not twisted toward the machine.",
        "Pull the handle diagonally across your body from high to low, moving from your shoulder down toward the opposite hip. Rotate through your torso and hips as you pull, but keep your lower body stable. Your arms stay extended throughout the movement, and your core should control the chop.",
        "Finish with the handle near your opposite hip, with your torso rotated slightly. Slowly return to the start position, controlling the movement. You should feel this in your obliques, core, and shoulders. Avoid using just your arms or letting your back round—focus on using your core to drive the movement.",
        "Repeat with opposite side."
      ],
      balance: BalanceType.bilateral,
      balanceLevel: BalanceLevel.static,
      body: [BodyFocus.full, BodyFocus.core],
      contraction: ContractionType.isotonic,
      equipment: [Equipment.cable_machine],
      joint: [Joint.shoulder, Joint.elbow, Joint.hip, Joint.knee],
      lift: LiftType.compound,
      muscles: [MuscleGroup.lats, MuscleGroup.obliques, MuscleGroup.abs],
      pattern: [MovementPattern.pull, MovementPattern.rotational, MovementPattern.core],
      plane: [MovementPlane.sagittal, MovementPlane.transverse, MovementPlane.frontal],
      muxPlaybackId: "rVEb9AaVBs3nVgWYTgAU01YFUGbQ8z7Y022XbntnEXyV4",
    },
    {
      name: "Standing Cable Lift",
      description: "A full body core exercise that improves rotational power and stability",
      tags: ["functional", "stability", "rotation"],
      cues: [
        "Attach a handle to the cable machine at the lowest setting. Stand sideways to the machine with your feet shoulder-width apart and knees slightly bent. Hold the handle with both hands, arms extended, starting near your hip closest to the machine. Engage your core, keeping your hips and shoulders square.",
        "Lift the handle diagonally across your body from low to high, moving from your hip toward the opposite shoulder. Rotate through your torso and hips as you lift, but keep your lower body stable. Your arms should stay extended, and the movement should be driven by your core, not just your arms.",
        "Finish with the handle near your opposite shoulder, with your torso slightly rotated. Slowly return to the starting position in a controlled manner. You should feel this in your obliques, core, and shoulders. Avoid relying on your arms or arching your back—focus on using your core to lift the weight.",
        "Repeat with opposite side."
      ],
      balance: BalanceType.bilateral,
      balanceLevel: BalanceLevel.static,
      body: [BodyFocus.full, BodyFocus.core],
      contraction: ContractionType.isotonic,
      equipment: [Equipment.cable_machine],
      joint: [Joint.shoulder, Joint.elbow, Joint.hip, Joint.knee, Joint.ankle],
      lift: LiftType.compound,
      muscles: [MuscleGroup.lats, MuscleGroup.obliques, MuscleGroup.abs, MuscleGroup.erectors, MuscleGroup.shoulders],
      pattern: [MovementPattern.pull, MovementPattern.rotational, MovementPattern.core, MovementPattern.push],
      plane: [MovementPlane.sagittal, MovementPlane.transverse, MovementPlane.frontal],
      muxPlaybackId: "J3UeencZvHDF9hhnA44IPY00xLrx00ybVcfeEON02be4z4",
    },
    {
      name: "Tall Kneeling Cable Anti Rotation Hold",
      description: "A full body core exercise that improves rotational stability",
      tags: ["functional", "stability", "rotation"],
      cues: [
        "Attach a handle to the cable machine at about chest height. Kneel on the ground in a tall kneeling position (both knees on the floor) with your body facing perpendicular to the cable machine. Your knees should be hip-width apart, and your hips fully extended. Hold the cable handle with both hands, arms extended straight in front of you at chest level. Keep your core engaged, shoulders back, and spine in a neutral position.",
        "Pull the handle out in front of your chest with your arms fully extended, keeping the cable from pulling you toward the machine. Resist rotation by engaging your core, shoulders, and glutes to keep your torso square and stable. Do not let the cable twist or rotate your body—maintain a strong, steady posture.",
        "Hold the position for the prescribed time, then slowly return the handle to the starting position. You should feel this in your obliques, core, and glutes, with your shoulders working to stabilize the movement. Avoid arching your back or letting your hips shift—stay tall and firm throughout the hold.",
        "Repeat with opposite side."
      ],
      balance: BalanceType.bilateral,
      balanceLevel: BalanceLevel.static,
      body: [BodyFocus.core],
      contraction: ContractionType.isometric,
      equipment: [Equipment.cable_machine],
      joint: [Joint.shoulder, Joint.elbow, Joint.hip, Joint.knee],
      lift: LiftType.isolation,
      muscles: [MuscleGroup.obliques, MuscleGroup.abs, MuscleGroup.erectors, MuscleGroup.shoulders],
      pattern: [MovementPattern.rotational, MovementPattern.core],
      plane: [MovementPlane.sagittal, MovementPlane.transverse],
      muxPlaybackId: "sFaVdiBlu01J6HwfpFo83ukkfV29mKGUrlYIVCC5oEi8",
    },
    {
      name: "Tall Kneeling Cable Anti Rotation Pallof Press",
      description: "A full body core exercise that improves rotational stability",
      tags: ["functional", "stability", "rotation"],
      cues: [
        "Attach a handle to the cable machine at about chest height. Kneel on the ground in a tall kneeling position (both knees on the floor) with your body facing perpendicular to the cable machine. Your knees should be hip-width apart, and your hips fully extended. Hold the cable handle with both hands, arms extended straight in front of you at chest level. Keep your core engaged, shoulders back, and spine in a neutral position.",
        "Press the handle straight out in front of you, extending your arms fully without allowing your body to rotate. Keep your torso stable and your arms in a straight line as you push the cable away from your chest. Once fully extended, hold for a moment, then slowly bring the handle back to your chest, resisting the cable's pull throughout the movement.",
        "Repeat the pressing motion for the prescribed number of reps. You should feel this in your core, especially your obliques, as you resist rotation. Your glutes, shoulders, and chest will also work to stabilize the movement. Avoid letting your back arch or your hips shift—maintain a solid, tall posture throughout.",
        "Repeat with opposite side."
      ],
      balance: BalanceType.bilateral,
      balanceLevel: BalanceLevel.dynamic,
      body: [BodyFocus.core, BodyFocus.upper],
      contraction: ContractionType.isometric,
      equipment: [Equipment.cable_machine],
      joint: [Joint.shoulder, Joint.elbow, Joint.hip, Joint.knee],
      lift: LiftType.compound,
      muscles: [MuscleGroup.obliques, MuscleGroup.abs, MuscleGroup.erectors, MuscleGroup.shoulders, MuscleGroup.pecs],
      pattern: [MovementPattern.rotational, MovementPattern.core, MovementPattern.push],
      plane: [MovementPlane.sagittal, MovementPlane.transverse],
      muxPlaybackId: "tG1R00di01E02CnddXquQQilFpRlSqLg55aw4niXIOvkxA",
    },
    {
      name: "Suspension Row",
      description: "A full body pull exercise",
      tags: ["functional", "suspension"],
      cues: [
        "Stand facing the TRX or rings, holding the handles with both hands. Walk your feet forward and lean back so your body is at an angle, keeping your core tight and your body in a straight line from head to heels. The more horizontal your body, the more challenging the exercise will be. Start with your arms fully extended in front of you, shoulders down, and your palms facing each other.",
        "Pull your chest toward the handles by driving your elbows back, squeezing your shoulder blades together. Keep your body in a plank position throughout the movement. Your elbows should stay close to your body, and your wrists should stay neutral (don't let them bend).",
        "Lower yourself back to the starting position with control, fully extending your arms. You should feel this in your upper back, lats, and biceps. Maintain tension in your core throughout the movement, and avoid shrugging your shoulders or letting your hips sag.",
      ],
      balance: BalanceType.bilateral,
      balanceLevel: BalanceLevel.static,
      body: [BodyFocus.core, BodyFocus.upper],
      contraction: ContractionType.isotonic,
      equipment: [Equipment.gymnastics_rings, Equipment.suspension],
      joint: [Joint.shoulder, Joint.elbow, Joint.wrist],
      lift: LiftType.compound,
      muscles: [MuscleGroup.lats, MuscleGroup.biceps, MuscleGroup.shoulders],
      pattern: [MovementPattern.pull],
      plane: [MovementPlane.sagittal],
      muxPlaybackId: "yNTTTsacFF9K4vf02QwlFn7RWZDStq3T00hwrmnqw5cF4",
    },
    {
      name: "V Stance Thoracic Spine Mobility",
      description: "A thoracic spine mobility exercise",
      tags: ["functional", "mobility"],
      cues: [
        "Stand with your feet in a wide stance, wider than shoulder-width, creating a \"V\" shape with your legs. Keep your knees slightly bent and hinge at the hips, lowering your torso toward the floor with a flat back. Place one hand on the ground directly beneath your chest, or on a block for support, while the other arm is relaxed by your side.",
        "Rotate your torso to one side, lifting your free arm up toward the ceiling, following it with your eyes. Keep your hips stable and focus on rotating through your thoracic spine (mid-back), not just your shoulders or lower back. Reach as far as you can while maintaining good form.",
        "Hold the rotation briefly at the top, then return to the starting position and switch sides. You should feel a deep stretch and mobility through your thoracic spine, as well as your chest and upper back. Avoid rotating through your lower back or hips—keep the movement focused on the upper spine. Maintain a neutral, strong core throughout.",
        "Repeat with opposite arm."
      ],
      balance: BalanceType.bilateral,
      balanceLevel: BalanceLevel.static,
      body: [BodyFocus.upper],
      equipment: [Equipment.bodyweight],
      joint: [Joint.shoulder, Joint.hip],
      muscles: [MuscleGroup.lats, MuscleGroup.shoulders],
      pattern: [MovementPattern.rotational],
      plane: [MovementPlane.transverse],
      stretch: StretchType.dynamic,
      muxPlaybackId: "5a5ziapKMdlI01rLQqzA3f93Fo1xrpHIkR02g8GCGq1008",
    },
    {
      name: "W Pulldowns",
      description: "A upper body vertical pull exercise",
      tags: ["functional", "back"],
      cues: [
        "Attach a bar or handles to the cable machine at a high setting. Sit or kneel facing the machine with your knees comfortably bent and feet flat on the ground. Grip the handles or bar with your palms facing each other (neutral grip), and your arms extended overhead in a \"Y\" shape. Engage your core and sit up tall with your shoulders relaxed away from your ears.",
        "Pull the handles or bar down toward your shoulders while bending your elbows and bringing them down and back to form a \"W\" shape with your arms. Squeeze your shoulder blades together as you pull, keeping your chest lifted and your torso stable. Your elbows should stay in line with your shoulders and move down and back, not out to the sides.",
        "Pause briefly at the bottom of the movement, then slowly return the handles or bar to the starting position with control. You should feel this in your upper back, shoulders, and lats. Avoid letting your shoulders shrug or your back arch—maintain a strong, engaged core throughout the movement.",
      ],
      balance: BalanceType.bilateral,
      balanceLevel: BalanceLevel.static,
      body: [BodyFocus.upper],
      equipment: [Equipment.cable_machine],
      joint: [Joint.shoulder, Joint.elbow, Joint.wrist],
      muscles: [MuscleGroup.lats, MuscleGroup.shoulders, MuscleGroup.biceps],
      pattern: [MovementPattern.pull],
      plane: [MovementPlane.frontal],
      muxPlaybackId: "AbyDWdldxxJG72KnkGTTk74Xolx4Hf84GyMnhEz200TM",
    },
    {
      name: "X Pulldowns",
      description: "A upper body vertical pull exercise",
      tags: ["functional", "back"],
      cues: [
        "Set up two cables at a high setting, with each handle on opposite sides of a cable machine. Stand in the center of the machine, facing forward, with feet shoulder-width apart. Grab the left handle with your right hand and the right handle with your left hand, forming an \"X\" shape in front of you. Extend your arms fully, palms facing down, and engage your core, keeping your torso upright and chest up.",
        "Pull the handles down and outward diagonally toward your hips while bending your elbows and bringing them toward your sides. Squeeze your shoulder blades together as you pull, keeping your chest lifted. Your arms should cross in front of you at the start and uncross as you pull down, maintaining control of the cables.",
        "Finish with your elbows at your sides and a slight pause to feel the squeeze in your upper back and lats. Slowly return to the starting position, letting the cables cross again at the top. You should feel this in your lats, shoulders, and upper back. Keep your core tight and avoid arching your lower back or letting your shoulders shrug.",
      ],
      balance: BalanceType.bilateral,
      balanceLevel: BalanceLevel.static,
      body: [BodyFocus.upper],
      equipment: [Equipment.cable_machine],
      joint: [Joint.shoulder, Joint.elbow, Joint.wrist],
      muscles: [MuscleGroup.lats, MuscleGroup.shoulders, MuscleGroup.biceps],
      pattern: [MovementPattern.pull],
      plane: [MovementPlane.frontal],
      muxPlaybackId: "GTy01N9EDc023ZE02QRVUPaF7eDaiurrnyO5z2W6oo8VTo",
    },
    {
      name: "Pushup",
      description: "An full body strength exercise that targets chest and core",
      tags: ["chest", "core", "calisthenics"],
      cues: [
        "Start in a high plank position with your hands slightly wider than shoulder-width apart. Your body should form a straight line from your head to your heels, with your core engaged and your glutes tight. Keep your shoulders directly above your wrists, and your feet together or hip-width apart, depending on your stability.",
        "Lower your body by bending your elbows, keeping them at a 45-degree angle from your body (not flaring out to the sides). Your chest should lower toward the floor while maintaining a straight line from your head to your heels. Keep your core braced to prevent your hips from sagging or rising too high.",
        "Push through your hands to return to the starting position, fully extending your arms. You should feel this in your chest, shoulders, triceps, and core. Focus on maintaining a tight plank throughout the movement, avoiding any arching in your lower back or letting your hips drop. Maintain control on the way down and up."
      ],
      balance: BalanceType.bilateral,
      balanceLevel: BalanceLevel.static,
      body: [BodyFocus.upper, BodyFocus.core],
      contraction: ContractionType.isotonic,
      equipment: [Equipment.bodyweight],
      joint: [Joint.ankle, Joint.shoulder, Joint.wrist, Joint.elbow],
      lift: LiftType.compound,
      muscles: [MuscleGroup.pecs, MuscleGroup.triceps, MuscleGroup.shoulders, MuscleGroup.abs, MuscleGroup.erectors],
      pattern: [MovementPattern.push, MovementPattern.core],
      plane: [MovementPlane.sagittal],
      muxPlaybackId: "nepxkswcJlH82X26jnzEKAeol2qbTlTAM9FWdytsseE",
    },
  ]
}

async function deleteAll() {
  await db.user.deleteMany();
  await db.exercise.deleteMany();
  await db.coach.deleteMany();
  await db.program.deleteMany();
}

async function createAll() {
  await createUser();
  await createAdmin();
  await Promise.all([
    ...getKettlebellExercises().map((exercise) => db.exercise.create({ data: exercise })),
    ...getAthleticConditioningExercises().map((exercise) => db.exercise.create({ data: exercise })),
    ...getCoaches().map((coach) => db.coach.create({ data: coach })),
  ]);
}

async function seed() {
  console.log('Start seeding ...');
  try {
    await deleteAll();
    console.log('Deleted all previous data ...');
    await createAll();
    console.log('Seed completed successfully');
  } catch (error) {
    console.error('Seed failed:', error);
    throw error;
  }
};

seed();